### ISSUE TITLE
Unable to go below 30 MHz

### ISSUE THREAD

**Issue by abanerjee123** [nqrduck/nqrduck-spectrometer-limenqr#14]
I am actually interested in some low frequency NQR (700-900 KHz). But It is now allowing it to go below 30 MHz. May be I am missing something. Loopback test is working above 30 MHz.

Also I need help to set up the gate pulse. Where I should connect the 12V and the gate output. bit confused. any help will be appreciated.
Thanks
![LimeSDR](https://github.com/user-attachments/assets/bcd9d97b-02af-4edf-8d8e-b2c399f827aa)

**Comment by jupfi** [comment]
Hi, 

this is the LimeSDR Mini 2.4. I primarily used the LimeSDR USB https://www.crowdsupply.com/lime-micro/limesdr in the past. 
So I haven't tested the TTL stuff for the LimeMini very extensively. I will try to find some time to test this stuff.
